### ISSUE TITLE
sed command fails on macos 11.6

### ISSUE THREAD

**Issue by christof-b** [markomitranic/docker-mac-vagrant#7]
I followed the simple steps to setup everything and start up, but the trigger-up.sh script failed during execution of
`vagrant up`

Error Message:
workbox: sed: 1: "/Users/.../.ssh/config": command c expects \ followed by text

The reason for this seems to be different behavior of sed on different versions of macos.
See https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

For me it worked after adding a backup suffix to the sed command in trigger-up.sh, like:
`# Prepend content to the start of the file
    sed -i .bak '1s;^;Include config.d/*'"\\${nl}\\${nl}"';' "$HOME/.ssh/config"`

But maybe the use of the -e flag as suggested in stackoverflow, could avoid a os switch to resolve this issue.

**Comment by borisceranic** [comment]
Hi @christof-b,

Ahhh - good catch, thanks! I completely forgot about the necessity to pass an argument to `-i`.

Besides, it's a good idea anyhow to back up files sed edits in-place. I'll submit a PR that should fix this issue. Stay tuned.

**Comment by borisceranic** [comment]
@christof-b Could you spare a few minutes to try applying the change introduced in #8 to your `trigger-up.sh` script locally and let me know if it works for you as expected?

Then we can merge #8.

**Comment by borisceranic** [comment]
This issue got closed automatically because #8 was merged.

@christof-b Can you please pull the latest code from the main branch and let us know if the error is gone for you? Thanks.

**Comment by markomitranic** [comment]
A month has passed in radio silence. I will consider this bug to be resolved until it pops up again.

Closing
